name: SimpleWebhooks
version: 1.0
description: A simple plugin for sending data to webhooks.
author: Kyle Nanakdewa
website: http://Akenland.com/plugins

main: com.kylenanakdewa.simplewebhooks.WebhooksPlugin
softdepend: [dynmap, CoRE]

commands:
  webhooks:
    description: View plugin information, reload the plugin, and execute webhooks.
    permission: webhooks.admin
    usage: /webhooks <version/list/reload/execute> [webhook name] [params...]
  translate:
    description: Translate chat messages.
    usage: /translate <message> OR /translate -set <language code>